### ISSUE TITLE
LICENSE file hyperlinks to nowwhere  

### ISSUE THREAD

**Issue by IoTman** [intel-iot-devkit/concurrent-video-analytic-pipeline-optimization-sample-l#10]
The LICENSE link in this sample should point to an MIT and Intel license file, for example https://github.com/intel-iot-devkit/Industrial-Anomaly-Detection/blob/master/LICENSE.md

**Comment by maozhong1** [comment]
please refer to below link
https://github.com/intel-iot-devkit/concurrent-video-analytic-pipeline-optimization-sample-l/blob/master/video_e2e_sample/LICENSE
